version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: www
      POSTGRES_PASSWORD: www_02064037fec7
      POSTGRES_DB: postrges
    ports:
      - "5432:5432"
    networks:
      - bot_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: telegram_auction_bot
    restart: always
    environment:
      BOT_TOKEN : 7194084241:AAEeDGexPRweq7mf0pqUDcCIWkuHmnSmgRw
      DB_URL : postgresql+asyncpg://www:www_02064037fec7@localhost/postgres
      PAYMENTS_TOKEN : 1744374395:TEST:96d41625492547bab733
      CHANNEL_ID : -1001836551522
    depends_on:
      - db
    networks:
      - bot_network
    volumes:
      - .:/app

networks:
  bot_network:
    driver: bridge

volumes:
  postgres_data:
